---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-swarm-emai-io-v1alpha2-kaiinstance
  failurePolicy: Fail
  name: vkaiinstance-v1alpha2.kb.io
  rules:
  - apiGroups:
    - swarm.emai.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - kaiinstances
  sideEffects: None
