apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboarding
  labels:
    app: onboarding
    app.kubernetes.io/name: onboarding
    app.kubernetes.io/part-of: swarm-system
    emai.io/role: onboarding
