apiVersion: v1
kind: ServiceAccount
metadata:
  name: onboarding
  namespace: emai-swarm
  labels:
    app: onboarding
    app.kubernetes.io/name: onboarding
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: onboarding
