apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace
  labels:
    app: workspace
    app.kubernetes.io/name: workspace
    app.kubernetes.io/part-of: swarm-system
    emai.io/role: workspace
