apiVersion: v1
kind: ServiceAccount
metadata:
  name: workspace
  namespace: emai-swarm
  labels:
    app: workspace
    app.kubernetes.io/name: workspace
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: workspace
