/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0
*/

// Package v1alpha2 hosts the validating-admission webhook for KaiInstance
// (TASK-015 Phase 2). The webhook rejects creates/updates whose
// `spec.resources` exceed the tier's ceiling in pkg/quotas, before the
// operator's reconciler ever sees the object. The operator-side
// ClampResources still runs after admission as a safety net for legacy
// internal-managed tenants that bypass the webhook scope.
package v1alpha2

import (
	"context"
	"fmt"
	"strings"

	ctrl "sigs.k8s.io/controller-runtime"
	logf "sigs.k8s.io/controller-runtime/pkg/log"
	"sigs.k8s.io/controller-runtime/pkg/webhook/admission"

	swarmv1alpha2 "github.com/emai-ai/swarm-operator/api/v1alpha2"
	"github.com/emai-ai/swarm/pkg/quotas"
)

// SetupKaiInstanceWebhookWithManager registers the validating webhook against
// the manager's webhook server. controller-runtime computes the path as
// `/validate-swarm-emai-io-v1alpha2-kaiinstance` from the GVK; the kustomize
// scaffold in `config/webhook/manifests.yaml` (generated by `make manifests`
// from the +kubebuilder:webhook marker below) declares the same path on the
// ValidatingWebhookConfiguration so cluster + binary agree.
func SetupKaiInstanceWebhookWithManager(mgr ctrl.Manager) error {
	return ctrl.NewWebhookManagedBy(mgr, &swarmv1alpha2.KaiInstance{}).
		WithValidator(&KaiInstanceValidator{}).
		Complete()
}

// +kubebuilder:webhook:path=/validate-swarm-emai-io-v1alpha2-kaiinstance,mutating=false,failurePolicy=fail,sideEffects=None,groups=swarm.emai.io,resources=kaiinstances,verbs=create;update,versions=v1alpha2,name=vkaiinstance-v1alpha2.kb.io,admissionReviewVersions=v1

// KaiInstanceValidator implements admission.Validator[*KaiInstance] for
// v1alpha2. SaaS-enrolled tenants (`spec.tier` set + `spec.managed !=
// "internal"`) are validated against the tier ceiling; legacy /
// internal-managed tenants pass through (their resource sizing is
// hand-managed in `swarm-emai`).
type KaiInstanceValidator struct{}

// ensure KaiInstanceValidator implements the typed Validator interface.
var _ admission.Validator[*swarmv1alpha2.KaiInstance] = &KaiInstanceValidator{}

// ValidateCreate runs at the API server before a new KaiInstance is admitted.
func (v *KaiInstanceValidator) ValidateCreate(ctx context.Context, kai *swarmv1alpha2.KaiInstance) (admission.Warnings, error) {
	logf.FromContext(ctx).Info("validating KaiInstance create", "name", kai.Name, "tier", kai.Spec.Tier)
	return validateSpec(&kai.Spec)
}

// ValidateUpdate is the same check on every spec.update — operators change tiers
// in-place (free → starter upgrade), and the resources that fit free might not
// fit the higher-tier defaults; we re-check on every update.
func (v *KaiInstanceValidator) ValidateUpdate(ctx context.Context, _, newObj *swarmv1alpha2.KaiInstance) (admission.Warnings, error) {
	logf.FromContext(ctx).Info("validating KaiInstance update", "name", newObj.Name, "tier", newObj.Spec.Tier)
	return validateSpec(&newObj.Spec)
}

// ValidateDelete is a no-op — deletes don't need quota checks.
func (v *KaiInstanceValidator) ValidateDelete(_ context.Context, _ *swarmv1alpha2.KaiInstance) (admission.Warnings, error) {
	return nil, nil
}

// validateSpec is the actual rule body. Pulled out so create/update share the
// same logic. SaaS-enrolled means the tenant opted into tier enforcement;
// legacy + internal tenants skip.
func validateSpec(spec *swarmv1alpha2.KaiInstanceSpec) (admission.Warnings, error) {
	if !isSaaSEnrolled(spec) {
		return nil, nil
	}
	tier := quotas.Tier(spec.Tier)
	if !quotas.ValidTier(tier) {
		return nil, fmt.Errorf("spec.tier %q is not a known SaaS tier (free/starter/growth/enterprise)", spec.Tier)
	}
	violations := quotas.ResourceViolations(spec.Resources, tier)
	if len(violations) == 0 {
		return nil, nil
	}
	return nil, fmt.Errorf("spec.resources exceed %s tier limits: %s", tier, strings.Join(violations, "; "))
}

// isSaaSEnrolled mirrors the operator-side predicate: tenant has a tier set
// and is NOT explicitly managed=internal. Legacy tenants (no `tier`) and
// EmAI-internal tenants in `swarm-emai` (managed=internal) skip tier checks.
func isSaaSEnrolled(spec *swarmv1alpha2.KaiInstanceSpec) bool {
	if spec.Tier == "" {
		return false
	}
	if spec.Managed == "internal" {
		return false
	}
	return true
}
