apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-page
  labels:
    app: status-page
    app.kubernetes.io/name: status-page
    app.kubernetes.io/part-of: swarm-system
    emai.io/role: status
