apiVersion: v1
kind: ServiceAccount
metadata:
  name: status-page
  namespace: emai-swarm
  labels:
    app: status-page
    app.kubernetes.io/name: status-page
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: status
