apiVersion: v1
kind: Service
metadata:
  name: status-page
  labels:
    app: status-page
    component: web
spec:
  type: ClusterIP
  selector:
    app: status-page
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
