apiVersion: v1
kind: ServiceAccount
metadata:
  name: customer-chat
  namespace: emai-swarm
  labels:
    app: customer-chat
    app.kubernetes.io/name: customer-chat
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: customer-chat
