apiVersion: v1
kind: ServiceAccount
metadata:
  name: kira-central
  namespace: emai-swarm
  labels:
    app.kubernetes.io/name: kira-central
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: central
