apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: emai-swarm
  labels:
    app: chat
    component: web
spec:
  type: ClusterIP
  selector:
    app: chat
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
