apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat
  namespace: emai-swarm
  labels:
    app: chat
    app.kubernetes.io/name: chat
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: chat
