apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-console
  namespace: emai-swarm
  labels:
    app: admin-console
    app.kubernetes.io/name: admin-console
    app.kubernetes.io/part-of: emai-swarm
    emai.io/role: admin
