apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-console
  labels:
    app: admin-console
    app.kubernetes.io/name: admin-console
    app.kubernetes.io/part-of: swarm-system
    emai.io/role: admin
