#!/usr/bin/env bash
set -euo pipefail

# Provision a new customer OpenClaw instance.
# Usage: ./provision-customer.sh "Customer Name" "Project Name"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SWARM_DIR="$(dirname "$SCRIPT_DIR")"
DOCKER_DIR="$SWARM_DIR/docker"
TEMPLATE_DIR="$SWARM_DIR/agents/customer-template"

# --- Args ---
CUSTOMER_NAME="${1:?Usage: $0 \"Customer Name\" \"Project Name\"}"
PROJECT_NAME="${2:?Usage: $0 \"Customer Name\" \"Project Name\"}"
CUSTOMER_SLUG=$(echo "$CUSTOMER_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//;s/-$//')

echo "=== Provisioning customer: $CUSTOMER_NAME ==="
echo "    Slug: $CUSTOMER_SLUG"
echo "    Project: $PROJECT_NAME"

# --- Create customer directories ---
CUSTOMER_DIR="$SWARM_DIR/customers/$CUSTOMER_SLUG"
AGENT_DIR="$CUSTOMER_DIR/agent"
HQ_DIR="$CUSTOMER_DIR/headquarter"

if [ -d "$CUSTOMER_DIR" ]; then
    echo "ERROR: Customer directory already exists: $CUSTOMER_DIR"
    exit 1
fi

mkdir -p "$AGENT_DIR" "$HQ_DIR"
echo "    Created: $CUSTOMER_DIR"

# --- Initialize HQ with mc ---
echo "=== Initializing HQ repository ==="
if command -v mc &>/dev/null; then
    (cd "$HQ_DIR" && mc init --mode standalone --name "$CUSTOMER_SLUG")
    echo "    HQ initialized with mc"
else
    echo "WARNING: mc binary not found. HQ directory created but not initialized."
    echo "    Run 'mc init' manually in: $HQ_DIR"
fi

# --- Initialize git repo for HQ ---
(cd "$HQ_DIR" && git init && git add -A && git commit -m "Initial HQ setup for $CUSTOMER_NAME")
echo "    Git repo initialized"

# --- Render agent templates ---
echo "=== Rendering agent identity files ==="
for tmpl in "$TEMPLATE_DIR"/*.tmpl; do
    filename=$(basename "$tmpl" .tmpl)
    sed \
        -e "s/{{CUSTOMER_NAME}}/$CUSTOMER_NAME/g" \
        -e "s/{{CUSTOMER_SLUG}}/$CUSTOMER_SLUG/g" \
        -e "s/{{PROJECT_NAME}}/$PROJECT_NAME/g" \
        "$tmpl" > "$AGENT_DIR/$filename"
    echo "    Rendered: $filename"
done

# --- Generate Docker Compose override ---
OVERRIDE_FILE="$DOCKER_DIR/docker-compose.kai-${CUSTOMER_SLUG}.yml"
cat > "$OVERRIDE_FILE" <<YAML
# Auto-generated by provision-customer.sh
# Customer: $CUSTOMER_NAME
# Created: $(date -u +%Y-%m-%dT%H:%M:%SZ)

services:
  kai-${CUSTOMER_SLUG}:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: swarm-kai-${CUSTOMER_SLUG}
    volumes:
      - ../customers/${CUSTOMER_SLUG}/agent:/workspace/agent:ro
      - ../customers/${CUSTOMER_SLUG}/headquarter:/workspace/headquarter
    env_file: .env
    environment:
      - OPENCLAW_AGENT=kai-${CUSTOMER_SLUG}
      - OPENCLAW_PROVIDER=openrouter
      - OPENCLAW_MODEL=\${OPENCLAW_MODEL:-meta-llama/llama-3.3-70b-instruct:free}
    networks:
      - kai-${CUSTOMER_SLUG}-net
    restart: unless-stopped

networks:
  kai-${CUSTOMER_SLUG}-net:
    driver: bridge
    internal: true
YAML

echo "    Docker override: $OVERRIDE_FILE"

echo ""
echo "=== Provisioning complete ==="
echo ""
echo "To start the customer instance:"
echo "  cd $DOCKER_DIR"
echo "  docker compose -f docker-compose.yml -f docker-compose.kai-${CUSTOMER_SLUG}.yml up -d kai-${CUSTOMER_SLUG}"
echo ""
echo "To include in full stack:"
echo "  docker compose -f docker-compose.yml -f docker-compose.kai-${CUSTOMER_SLUG}.yml up -d"
